### ISSUE TITLE
Request support for non-ascii char

### ISSUE THREAD

**Issue by d4rkb1ue** [chrisbro/alfred-bear#1]
Thanks for your awesome work!

I need to search something besides English words. Could you please add other languages support?

Also, when doing `bst` search by tag, it just displays the tag name. Could you please add the note title on the list?

**Comment by chrisbro** [comment]
@d4rkb1ue Sure thing, let me take a look and see what I can do. I like the idea of also showing notes that match the tag.

**Comment by chrisbro** [comment]
@d4rkb1ue The latest release should handle both your non-ASCII issue and your feature request for adding notes into tag search - could you install [the latest alfred-bear.workflow](https://github.com/chrisbro/alfred-bear/releases/tag/0.2.0) release and try again?

**Comment by d4rkb1ue** [comment]
Wonderful! Thanks very very much! This workflow is really helpful!

**Comment by chrisbro** [comment]
Sounds like it works! I'll be closing this out, let me know if there's anything else I can do.
