### ISSUE TITLE
Search tag 'bst' broken by last update

### ISSUE THREAD

**Issue by kvndrsslr** [chrisbro/alfred-bear#18]
Apparently they not only changed the location but also the structure of the DB.
In my database, it is:
```
sqlite> .schema Z_6TAGS
CREATE TABLE Z_6TAGS ( Z_6NOTES INTEGER, Z_13TAGS INTEGER, PRIMARY KEY (Z_6NOTES, Z_13TAGS) );
CREATE INDEX Z_6TAGS_Z_13TAGS_INDEX ON Z_6TAGS (Z_13TAGS, Z_6NOTES);
```
In the queries you are using table Z_5TAGS with fields Z_5NOTES, Z_10TAGS.
I don't get why they would increment (version?) field names (???) but sadly, this happened. 

For me the following did the trick (fixed the search)

```
$ sed -i '' -e 's/Z_5/Z_6/g' -e 's/Z_10/Z_13/g' queries.py
```

**Comment by chrisbro** [comment]
Thanks for the heads up, and for the easy fix! I'll try to knock that out soon as well.

**Comment by chrisbro** [comment]
Should be good to go now with the latest release [here](https://github.com/chrisbro/alfred-bear/releases/download/0.3.3/alfred-bear.alfredworkflow). Thanks for the heads up @kvndrsslr !

**Comment by chrisbro** [comment]
Closing issue.
