### ISSUE TITLE
Search for a note and make it open in a new window?

### ISSUE THREAD

**Issue by swaroopch** [chrisbro/alfred-bear#19]
I'm willing to write a patch, but I couldn't figure out how to do it :)

Specifically referring to `new_window` parameter to [/open-note](https://bear.app/faq/X-callback-url%20Scheme%20documentation/#open-note)

**Comment by mdreynes** [comment]
change the workflow action in the Open Url node to "bear://x-callback-url/open-note?id={query}&new_window=yes"

**Comment by swaroopch** [comment]
Thanks @mdreynes , will check it out.
