### ISSUE TITLE
Tag search broken with Bear 1.7 update

### ISSUE THREAD

**Issue by mcburden** [chrisbro/alfred-bear#24]
![2019-09-06_14-04-33](https://user-images.githubusercontent.com/325631/64450097-6262b100-d0af-11e9-9cc6-91dd1d35e0fe.png)

**Comment by chrisbro** [comment]
Yep, just confirmed when I upgraded. They likely changed the underlying SQLite schema. I'll take a look.

**Comment by chrisbro** [comment]
@mcburden Should be fixed in [0.3.4](https://github.com/chrisbro/alfred-bear/releases/tag/0.3.4) - mind giving it a shot?

**Comment by mcburden** [comment]
Works great, thanks for the quick fix!
