### ISSUE TITLE
Search both title and content

### ISSUE THREAD

**Issue by psaniko** [chrisbro/alfred-bear#4]
Neat little workflow. Any chance you can add search through content or is that a problem performance-wise?

**Comment by chrisbro** [comment]
I think it'd work.  The hardest part would be figuring out how to combine and rank results - title matches first, then ones that match content? Any suggestions on what you'd like to see?

**Comment by chrisbro** [comment]
Or maybe two commands, one for title search and one for content search? Seems like it'd be better combined though.

**Comment by psaniko** [comment]
Combining them would be most useful I think. Probably direct title matches first, then content, as you suggested.

**Comment by chrisbro** [comment]
Done! You can get the latest release [here](https://github.com/chrisbro/alfred-bear/releases/tag/0.3.0).

**Comment by psaniko** [comment]
Thanks a lot, works like a charm!

**Comment by chrisbro** [comment]
@psaniko Excellent! I will likely want to explore some future functionality around showing the context of search results (so showing the words around the results).
